### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by nil-bsa2021** [nil-bsa2021/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by nil-odessa** [comment]
https://twitter.com/github Twitter
https://www.facebook.com/GitHub GitHub on Facebook
https://www.youtube.com/github GitHub on YouTube
https://www.linkedin.com/company/github GitHub on Linkedin
