### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by nil-bsa2021** [nil-bsa2021/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by nil-odessa** [comment]
<section>
	<h3>Tools</h3>
		<ul class="contacts">
			<li>
				<img src="https://github.githubassets.com/images/modules/site/features/launchpad/icons/icon-collaboration.svg" width="50" height="50">
				<span>Collaborative Coding</span>
			</li>
	  		<li>
				<img src="https://github.githubassets.com/images/modules/site/features/launchpad/icons/icon-automation.svg"  width="50" height="50">
				<span>Automation &amp; CI/CD</span>
			</li>
	  		<li>
				<img src="https://github.githubassets.com/images/modules/site/features/launchpad/icons/icon-security.svg"  width="50" height="50">
				<span>Security</span>
			</li>
	  		<li>
				<img src="https://github.githubassets.com/images/modules/site/features/launchpad/icons/icon-apps.svg"  width="50" height="50">
				<span>Client Apps</span>
			</li>
			<li>
				<img src="https://github.githubassets.com/images/modules/site/features/launchpad/icons/icon-project-management.svg"  width="50" height="50">
				<span>Project Management</span>
			</li>
			<li>
				<img src="https://github.githubassets.com/images/modules/site/features/launchpad/icons/icon-team-admin.png" width="50" height="50">
				<span>Team Administration</span>
			 </li>
			 <li>
				<img src="https://github.githubassets.com/images/modules/site/features/launchpad/icons/icon-community.svg" width="50" height="50">
				<span>Community</span>
			</li>
		</ul>
	</section>
    <section>
	  <h3>Languages</h3>
		  <div class="labels">
			<a rel="external" class="label" href="https://github.com/trending/javascript">JavaScript</a>		
			<a rel="external" class="label" href="https://github.com/trending/Pyton">Pyton</a>
			<a rel="external" class="label" href="https://github.com/trending/Java">Java</a>
			<a rel="external" class="label" href="https://github.com/trending/Go">Go</a>
			<a rel="external" class="label" href="https://github.com/trending/Ruby">Ruby</a>		
			<a rel="external" class="label" href="https://github.com/trending/c++">C++</a>
			<a rel="external" class="label" href="https://github.com/trending/TypeScript">TypeScript</a>
			<a rel="external" class="label" href="https://github.com/trending/php">PHP</a>
			<a rel="external" class="label" href="https://github.com/dotnet/csharplang">C#</a>		
			<a rel="external" class="label" href="https://github.com/trending/c">C</a>
			<a rel="external" class="label" href="https://github.com/trending/shell">Shell</a>
			<a rel="external" class="label" href="https://github.com/trending/scala">Scala</a>
			<a rel="external" class="label" href="https://github.com/trending/dart">Dart</a>		
			<a rel="external" class="label" href="https://github.com/trending/rust">Rust</a>
			<a rel="external" class="label" href="https://github.com/trending/cotlin">Cotlin</a>
			<a rel="external" class="label" href="https://github.com/trending/swift">Swift</a>	
			<a rel="external" class="label" href="https://github.com/trending/javascript">Groovy</a>		
			<a rel="external" class="label" href="https://github.com/trending/Pyton">Objective-C</a>
			<a rel="external" class="label" href="https://github.com/trending/Java">Elixir</a>
			<a rel="external" class="label" href="https://github.com/trending/Go">Perl</a>
			<a rel="external" class="label" href="https://github.com/trending/Ruby">CoffeeScript</a>		
			<a rel="external" class="label" href="https://github.com/trending/c++">Lua</a>
			<a rel="external" class="label" href="https://github.com/trending/PowerShell">PowerShell</a>
			<a rel="external" class="label" href="https://github.com/trending/TSQL">TSQL</a>		
			<a rel="external" class="label" href="https://github.com/trending/Erlang">Erlang</a>
			<a rel="external" class="label" href="https://github.com/trending/Clojure">Clojure</a>
			<a rel="external" class="label" href="https://github.com/trending/Haskell">Haskell</a>
			<a rel="external" class="label" href="https://github.com/trending/OCaml">OCaml</a>
			<a rel="external" class="label" href="https://github.com/trending/Jsonnet">Jsonnet</a>
			<a rel="external" class="label" href="https://github.com/trending/r">R</a>
			<a rel="external" class="label" href="https://github.com/trending/Coq">Coq</a>
			<a rel="external" class="label" href="https://github.com/trending/Julia">Julia</a>
			<a rel="external" class="label" href="https://github.com/trending/PureScript">PureScript</a>		
			<a rel="external" class="label" href="https://github.com/trending/Roff">Roff</a>
			<a rel="external" class="label" href="https://github.com/trending/Fortran">Fortran</a>		
			<a rel="external" class="label" href="https://github.com/trending/MATLAB">MATLAB</a>
			<a rel="external" class="label" href="https://github.com/trending/WebAssembly">WebAssembly</a>
			<a rel="external" class="label" href="https://github.com/dotnet/fsharp">F#</a>
			<a rel="external" class="label" href="https://github.com/trending/Puppet">Puppet</a>		
			<a rel="external" class="label" href="https://github.com/trending/Elm">Elm</a>
		  </div>	
	</section>
